import type { Metadata } from "next";
import { Barlow_Condensed } from "next/font/google";
import "./globals.scss";
import Header from "@/app/_components/Header/Header";
import Footer from "@/app/_components/Footer/Footer";

const barlowCondensed = Barlow_Condensed({
  weight: ["300", "400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlowCondensed.className} antialiased`}
      >
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
